### PR TITLE
feat: support nestjs ^10

### LINKED ISSUE #23: Support NestJs 10
Hello,

is it possible to add a versions which adds NestJS v10 as a peerDependency ?

### PR DESCRIPTION
**Pull request by teofilomonteiro**
Fixes #23

- Update version for nestjs 10 
- Update graphql dependencies + tests

### CODE REVIEW

**Comment by teofilomonteiro** [comment]
@whefter can you please give a review? :)

**Comment by masterambi** [comment]
@whefter

**Comment by kryptonpust** [comment]
@whefter

**Comment by whefter** [comment]
Somehow totally escaped my radar, thanks. Published in v1.10.0

**Pull request merged**
